spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/hrmsdb
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

fikrat:
  app:
    jwtSecret: SecretKey
    jwtExpirationMs: 86400000